### ISSUE TITLE
Cropping error

### ISSUE THREAD

**Issue by EnalisUs** [RizwanMunawar/yolov7-object-cropping#1]
Why u don't crop this ogirinal image to avoid the bounding box

**Comment by RizwanMunawar** [comment]
@EnalisUs! Code is cropping the image based on bounding boxes. without that, we can not crop the objects on image directly.

**Comment by EnalisUs** [comment]
you can crop this in original 

                    object_coordinates = [int(xyxy[0]),int(xyxy[1]),int(xyxy[2]),int(xyxy[3])]
                    imgc = cv2.imread(path)
                    cropobj = imgc[int(xyxy[1]):int(xyxy[3]),int(xyxy[0]):int(xyxy[2])]
                    crop_file_path = os.path.join("crop",str(crp_cnt)+".jpg")
                    cv2.imwrite(crop_file_path,cropobj)

**Comment by EnalisUs** [comment]
I try this in my local, and this is working. So u can update this in your repo
